name: Python CI/CD Pipeline 

on: 
  push:
    branches:
      - main
  pull_requests:

jobs: 
  buils:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint checker.py config.py || true

      - name: Run API checker
        run: python checker.py 